import { Role } from "@prisma/client";

export const PERMISSIONS = {
  VIEW_OWN_PROFILE: "VIEW_OWN_PROFILE",
  UPDATE_OWN_PROFILE: "UPDATE_OWN_PROFILE",
  DELETE_OWN_ACCOUNT: "DELETE_OWN_ACCOUNT",
  CHANGE_OWN_PASSWORD: "CHANGE_OWN_PASSWORD",
  VIEW_OWN_SESSIONS: "VIEW_OWN_SESSIONS",
  REVOKE_OWN_SESSIONS: "REVOKE_OWN_SESSIONS",

  VIEW_USERS: "VIEW_USERS",
  VIEW_USER_DETAIL: "VIEW_USER_DETAIL",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_USER_STATUS: "CHANGE_USER_STATUS",
  RESET_USER_PASSWORD: "RESET_USER_PASSWORD",
  VERIFY_USER_EMAIL: "VERIFY_USER_EMAIL",
  REVOKE_USER_SESSIONS: "REVOKE_USER_SESSIONS",
  VIEW_USER_STATS: "VIEW_USER_STATS",
  SEED_USERS: "SEED_USERS",

  MANAGE_MOVIES: "MANAGE_MOVIES",
  MANAGE_SHOWTIMES: "MANAGE_SHOWTIMES",
  MANAGE_SEATS: "MANAGE_SEATS",
  CHECK_IN_TICKETS: "CHECK_IN_TICKETS",
  VIEW_PARTNER_DASHBOARD: "VIEW_PARTNER_DASHBOARD",
  MANAGE_PARTNER_FINANCE: "MANAGE_PARTNER_FINANCE",

  MANAGE_EMAIL_TEMPLATES: "MANAGE_EMAIL_TEMPLATES",
  VIEW_SCHEDULED_EMAILS: "VIEW_SCHEDULED_EMAILS",
  SCHEDULE_USER_EMAILS: "SCHEDULE_USER_EMAILS",
  SEND_SYSTEM_EMAILS: "SEND_SYSTEM_EMAILS",
} as const;

export const PERMISSION_CODES = Object.values(PERMISSIONS);

export type PermissionCode = (typeof PERMISSION_CODES)[number];
export type EffectivePermission = PermissionCode | "*";

const USER_BASE_PERMISSIONS: PermissionCode[] = [
  PERMISSIONS.VIEW_OWN_PROFILE,
  PERMISSIONS.UPDATE_OWN_PROFILE,
  PERMISSIONS.DELETE_OWN_ACCOUNT,
  PERMISSIONS.CHANGE_OWN_PASSWORD,
  PERMISSIONS.VIEW_OWN_SESSIONS,
  PERMISSIONS.REVOKE_OWN_SESSIONS,
];

const PARTNER_PERMISSIONS: PermissionCode[] = [
  ...USER_BASE_PERMISSIONS,
  PERMISSIONS.MANAGE_MOVIES,
  PERMISSIONS.MANAGE_SHOWTIMES,
  PERMISSIONS.MANAGE_SEATS,
  PERMISSIONS.CHECK_IN_TICKETS,
  PERMISSIONS.VIEW_PARTNER_DASHBOARD,
  PERMISSIONS.MANAGE_PARTNER_FINANCE,
];

export const ROLE_PERMISSION_MAP: Record<Role, readonly EffectivePermission[]> = {
  [Role.ADMIN]: ["*"],
  [Role.PARTNER]: PARTNER_PERMISSIONS,
  [Role.USER]: USER_BASE_PERMISSIONS,
};

export const isPermissionCode = (value: string): value is PermissionCode =>
  PERMISSION_CODES.includes(value as PermissionCode);
