"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isPermissionCode = exports.ROLE_PERMISSION_MAP = exports.PERMISSION_CODES = exports.PERMISSIONS = void 0;
const client_1 = require("@prisma/client");
exports.PERMISSIONS = {
    VIEW_OWN_PROFILE: "VIEW_OWN_PROFILE",
    UPDATE_OWN_PROFILE: "UPDATE_OWN_PROFILE",
    DELETE_OWN_ACCOUNT: "DELETE_OWN_ACCOUNT",
    CHANGE_OWN_PASSWORD: "CHANGE_OWN_PASSWORD",
    VIEW_OWN_SESSIONS: "VIEW_OWN_SESSIONS",
    REVOKE_OWN_SESSIONS: "REVOKE_OWN_SESSIONS",
    VIEW_USERS: "VIEW_USERS",
    VIEW_USER_DETAIL: "VIEW_USER_DETAIL",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    CHANGE_USER_STATUS: "CHANGE_USER_STATUS",
    RESET_USER_PASSWORD: "RESET_USER_PASSWORD",
    VERIFY_USER_EMAIL: "VERIFY_USER_EMAIL",
    REVOKE_USER_SESSIONS: "REVOKE_USER_SESSIONS",
    VIEW_USER_STATS: "VIEW_USER_STATS",
    SEED_USERS: "SEED_USERS",
    MANAGE_MOVIES: "MANAGE_MOVIES",
    MANAGE_SHOWTIMES: "MANAGE_SHOWTIMES",
    MANAGE_SEATS: "MANAGE_SEATS",
    CHECK_IN_TICKETS: "CHECK_IN_TICKETS",
    VIEW_PARTNER_DASHBOARD: "VIEW_PARTNER_DASHBOARD",
    MANAGE_PARTNER_FINANCE: "MANAGE_PARTNER_FINANCE",
    MANAGE_EMAIL_TEMPLATES: "MANAGE_EMAIL_TEMPLATES",
    VIEW_SCHEDULED_EMAILS: "VIEW_SCHEDULED_EMAILS",
    SCHEDULE_USER_EMAILS: "SCHEDULE_USER_EMAILS",
    SEND_SYSTEM_EMAILS: "SEND_SYSTEM_EMAILS",
};
exports.PERMISSION_CODES = Object.values(exports.PERMISSIONS);
const USER_BASE_PERMISSIONS = [
    exports.PERMISSIONS.VIEW_OWN_PROFILE,
    exports.PERMISSIONS.UPDATE_OWN_PROFILE,
    exports.PERMISSIONS.DELETE_OWN_ACCOUNT,
    exports.PERMISSIONS.CHANGE_OWN_PASSWORD,
    exports.PERMISSIONS.VIEW_OWN_SESSIONS,
    exports.PERMISSIONS.REVOKE_OWN_SESSIONS,
];
const PARTNER_PERMISSIONS = [
    ...USER_BASE_PERMISSIONS,
    exports.PERMISSIONS.MANAGE_MOVIES,
    exports.PERMISSIONS.MANAGE_SHOWTIMES,
    exports.PERMISSIONS.MANAGE_SEATS,
    exports.PERMISSIONS.CHECK_IN_TICKETS,
    exports.PERMISSIONS.VIEW_PARTNER_DASHBOARD,
    exports.PERMISSIONS.MANAGE_PARTNER_FINANCE,
];
exports.ROLE_PERMISSION_MAP = {
    [client_1.Role.ADMIN]: ["*"],
    [client_1.Role.PARTNER]: PARTNER_PERMISSIONS,
    [client_1.Role.USER]: USER_BASE_PERMISSIONS,
};
const isPermissionCode = (value) => exports.PERMISSION_CODES.includes(value);
exports.isPermissionCode = isPermissionCode;
